packages:
  - "apps/*"
  - "packages/*"
  - "database"
allowBuilds:
  esbuild: true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  '@firebase/util': true
  protobufjs: true
onlyBuiltDependencies: esbuild
