import { PERMISSIONS, type Permission, type UserRole } from "@el-bannawy/shared";
import {
  Home,
  BookOpen,
  Users,
  Sparkles,
  BarChart3,
  Settings,
  Gamepad2,
  Trophy,
  Award,
  LifeBuoy,
  RefreshCw,
  ShoppingCart,
  Banknote,
  Coins,
  Database,
  Sliders,
  Bell,
  BellOff,
  BellRing,
  Calendar,
  FileText,
  Globe,
  Wrench,
  ScrollText,
  LibraryBig,
  Share2,
  Megaphone,
  type LucideIcon,
} from "lucide-react";

export interface NavModule {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly icon: LucideIcon;
  readonly route: string;
  readonly permission: Permission | null;
  readonly sidebar: boolean;
  readonly dashboard: boolean;
  readonly order: number;
  readonly category: "content" | "management" | "student" | "settings" | null;
  readonly roles?: readonly UserRole[];
}

export const NAV_REGISTRY: readonly NavModule[] = [
  {
    id: "home",
    title: "الرئيسية",
    description: "لوحة التحكم الرئيسية",
    icon: Home,
    route: "/dashboard",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 1,
    category: null,
  },
  {
    id: "units",
    title: "الوحدات التعليمية",
    description: "إنشاء وإدارة الوحدات التعليمية والدروس ومحتوى الدروس",
    icon: BookOpen,
    route: "/dashboard/units",
    permission: PERMISSIONS.UNITS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 10,
    category: "content",
  },
  {
    id: "stories",
    title: "قصص المنهج",
    description: "إنشاء وإدارة قصص المنهج وفصولها",
    icon: ScrollText,
    route: "/dashboard/stories",
    permission: PERMISSIONS.UNITS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 11,
    category: "content",
  },
  {
    id: "final-reviews",
    title: "المراجعات النهائية",
    description: "إنشاء وإدارة المراجعات النهائية ومحاضراتها",
    icon: LibraryBig,
    route: "/dashboard/final-reviews",
    permission: PERMISSIONS.UNITS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 12,
    category: "content",
  },
  {
    id: "live",
    title: "الحصص المباشرة",
    description: "إنشاء وإدارة الحصص المباشرة",
    icon: Users,
    route: "/dashboard/live",
    permission: PERMISSIONS.LIVE_VIEW,
    sidebar: true,
    dashboard: true,
    order: 40,
    category: "content",
  },
  {
    id: "secretary-live",
    title: "متابعة الحصص المباشرة",
    description: "متابعة الحصص المباشرة والاشتراكات",
    icon: Users,
    route: "/dashboard/live",
    permission: PERMISSIONS.LIVE_VIEW,
    sidebar: true,
    dashboard: true,
    order: 41,
    category: "management",
    roles: ["SECRETARY"],
  },
  {
    id: "ai",
    title: "اسأل البنا AI",
    description: "احصل على إجابات فورية وشروحات ومساعدة",
    icon: Sparkles,
    route: "/dashboard/ai",
    permission: PERMISSIONS.AI_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 50,
    category: "management",
    roles: ["STUDENT"],
  },
  {
    id: "ai-knowledge-base",
    title: "قاعدة المعرفة AI",
    description: "إدارة مصادر المعرفة للذكاء الاصطناعي",
    icon: Database,
    route: "/dashboard/ai/knowledge-base",
    permission: PERMISSIONS.AI_SETTINGS_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 51,
    category: "management",
  },
  {
    id: "ai-settings",
    title: "إعدادات AI",
    description: "إعدادات الذكاء الاصطناعي والنماذج والرصيد",
    icon: Sliders,
    route: "/dashboard/ai/settings",
    permission: PERMISSIONS.AI_SETTINGS_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 52,
    category: "management",
  },
  {
    id: "users",
    title: "المستخدمون",
    description: "إدارة الطلاب والمعلمين المسجلين",
    icon: Users,
    route: "/dashboard/users",
    permission: PERMISSIONS.STUDENTS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 60,
    category: "management",
  },
  {
    id: "reports",
    title: "التقارير",
    description: "إنشاء تقارير الأداء والتقدم",
    icon: BarChart3,
    route: "/dashboard/reports",
    permission: PERMISSIONS.REPORTS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 70,
    category: "management",
  },
  {
    id: "settings",
    title: "الإعدادات",
    description: "تعديل الإعدادات والتفضيلات",
    icon: Settings,
    route: "/dashboard/admin/settings",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 80,
    category: "settings",
  },
  {
    id: "ui-settings",
    title: "إعدادات الواجهة",
    description: "التحكم في ألوان الواجهة والخطوط والخلفيات",
    icon: Sliders,
    route: "/dashboard/admin/ui-settings",
    permission: PERMISSIONS.UI_SETTINGS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 81,
    category: "settings",
  },
  {
    id: "mistakes",
    title: "تعلم من أخطائك",
    description: "راجع الإجابات الخاطئة وحسن مستواك",
    icon: RefreshCw,
    route: "/dashboard/mistakes",
    permission: PERMISSIONS.MISTAKES_VIEW,
    sidebar: true,
    dashboard: true,
    order: 90,
    category: "student",
    roles: ["STUDENT"],
  },
  {
    id: "games",
    title: "الألعاب التعليمية",
    description: "العب ألعاباً لتحسين المفردات والقواعد والقراءة",
    icon: Gamepad2,
    route: "/dashboard/games",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 100,
    category: "student",
    roles: ["STUDENT"],
  },
  {
    id: "teacher-games",
    title: "إدارة الألعاب",
    description: "اضبط إعدادات الألعاب التعليمية",
    icon: Gamepad2,
    route: "/dashboard/teacher/games",
    permission: PERMISSIONS.VOCABULARY_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 67,
    category: "management",
  },
  {
    id: "achievements",
    title: "الإنجازات",
    description: "تابع إنجازاتك التعليمية",
    icon: Award,
    route: "/dashboard/achievements",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 110,
    category: "student",
    roles: ["STUDENT"],
  },
  {
    id: "leaderboard",
    title: "العباقرة",
    description: "قائمة المتصدرين",
    icon: Trophy,
    route: "/dashboard/leaderboard",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 120,
    category: "student",
    roles: ["STUDENT"],
  },
  {
    id: "competitions",
    title: "المسابقات",
    description: "أنشئ المسابقات وتنافس مع الطلاب",
    icon: Gamepad2,
    route: "/dashboard/competitions",
    permission: PERMISSIONS.COMPETITION_VIEW,
    sidebar: true,
    dashboard: false,
    order: 125,
    category: "student",
  },
  {
    id: "coins",
    title: "العملات والمحتوى المدفوع",
    description: "باقات العملات وأسعار الفتح ورموز التفعيل وطلبات فتح المحتوى",
    icon: Coins,
    route: "/dashboard/admin/coins",
    permission: PERMISSIONS.COINS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 66,
    category: "management",
  },
  {
    id: "payments",
    title: "طلبات الدفع والتحويلات",
    description: "مراجعة طلبات شراء العملات وأرقام التحويل",
    icon: Banknote,
    route: "/dashboard/admin/payments",
    permission: PERMISSIONS.COINS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 67,
    category: "management",
  },
  {
    id: "communication",
    title: "التواصل والدعم",
    description: "روابط التواصل الاجتماعي وبيانات الدعم الفني",
    icon: Globe,
    route: "/dashboard/admin/communication",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 68,
    category: "management",
  },
  {
    id: "page-status",
    title: "حالة الصفحات والصيانة",
    description: "التحكم في توفر صفحات المنصة ووضع الصيانة للطلاب",
    icon: Wrench,
    route: "/dashboard/admin/page-status",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 69,
    category: "management",
  },
  {
    id: "saved-pdfs",
    title: "الملفات المحفوظة",
    description: "PDF الملفات المحفوظة للوصول السريع",
    icon: FileText,
    route: "/dashboard/saved-pdfs",
    permission: PERMISSIONS.SAVED_PDFS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 95,
    category: "student",
    roles: ["STUDENT"],
  },
  {
    id: "support",
    title: "الدعم الفني",
    description: "تواصل مع فريق الدعم",
    icon: LifeBuoy,
    route: "/dashboard/support",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 130,
    category: "student",
  },
  {
    id: "notifications",
    title: "الإشعارات",
    description: "عرض الإشعارات الخاصة بك",
    icon: Bell,
    route: "/dashboard/notifications",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 125,
    category: null,
  },
  {
    id: "notification-preferences",
    title: "تفضيلات الإشعارات",
    description: "التحكم في أنواع الإشعارات التي تستلمها",
    icon: BellOff,
    route: "/dashboard/notifications/preferences",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 124,
    category: null,
  },
  {
    id: "admin-notifications",
    title: "إعدادات الإشعارات",
    description: "التحكم في أنواع الإشعارات وواتس آب",
    icon: BellRing,
    route: "/dashboard/admin/notifications",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 72,
    category: "management",
  },
  {
    id: "lesson-schedules",
    title: "مواعيد الفرق",
    description: "تحديد أيام توفر الحصص لكل فرقة",
    icon: Calendar,
    route: "/dashboard/admin/lesson-schedules",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 73,
    category: "management",
  },
  {
    id: "shop",
    title: "المتجر",
    description: "اشتر العملات وافتح المحتوى",
    icon: ShoppingCart,
    route: "/dashboard/shop",
    permission: PERMISSIONS.COINS_PURCHASE,
    sidebar: true,
    dashboard: true,
    order: 135,
    category: "student",
    roles: ["STUDENT"],
  },
  {
    id: "referral",
    title: "ادعُ أصدقاءك",
    description: "شارك كود الدعوة واحصل على مكافآت عند اشتراك أصدقائك",
    icon: Share2,
    route: "/dashboard/referral",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 136,
    category: "student",
    roles: ["STUDENT"],
  },
  {
    id: "admin-referrals",
    title: "دعوة الأصدقاء",
    description: "إدارة حملات الدعوة ومكافآت الاشتراك ودعوات الطلاب",
    icon: Megaphone,
    route: "/dashboard/admin/referrals",
    permission: PERMISSIONS.REFERRALS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 65,
    category: "management",
  },
] as const;

export function getSidebarModules(can: (p: Permission) => boolean, role: UserRole | undefined): readonly NavModule[] {
  return NAV_REGISTRY.filter(
    (m) =>
      m.sidebar &&
      (m.permission === null || can(m.permission)) &&
      (m.roles === undefined || (role !== undefined && m.roles.includes(role))),
  );
}

export function getDashboardModules(can: (p: Permission) => boolean, role: UserRole | undefined): readonly NavModule[] {
  return NAV_REGISTRY.filter(
    (m) =>
      m.dashboard &&
      m.permission !== null &&
      can(m.permission) &&
      (m.roles === undefined || (role !== undefined && m.roles.includes(role))),
  );
}
